x<-c("tidyverse", "dplyr", "lubridata","ggplot2")
lapply(x, require, character.only = TRUE)
setwd("C:/Users/aparihar/Documents/GitHub/elo_recommendation/dataset")
train <- read_csv("train.csv")
test <- read_csv("test.csv")
histdata <- read_csv("historical_transactions.csv",nrows=1000)
newdata <- read_csv("new_merchant_transactions.csv",nrows=1000)
merchants <- read_csv("merchants.csv")
sample <- read_csv("sample_submission.csv")